title: mimavox
theme: charlolamode

menu:
  main:
      - name: Code
        url: /code/
        weight: 30
      - name: Research
        url: /research/
        weight: 20
      - name: Articles
        url: /articles/
        weight: 15

params:
  author: Andreas Chatzopoulos
  ShowReadingTime: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: false

  profileMode:
    # Disable to populate home page with 'mainSections' content
    enabled: true
    title: Andreas Chatzopoulos
    description: |

      University lecturer with a background in Cognitive
      Science and extensive programming experience
    
    # Profile image in theme's static/images
    imageUrl: "/images/profile.png"
    imageTitle: Andreas Chatzopoulos
    buttons:
    - name: CV (PDF)
      url: /cv.pdf

  # Available icons (more in svg.html): codepen, cv, dev, discord, email, goodreads, googlescholar, instagram, linkedin, medium, matrix, phone, researchgate, telegram, youtube
  socialIcons:
    - name: mastodon
      url: "https://zirk.us/home"
    - name: github
      url: "https://github.com/mimavox"
    - name: linkedin
      url: "https://www.linkedin.com/in/chatzopoulos/"
    - name: researchgate
      url: "https://www.researchgate.net/profile/Andreas-Chatzopoulos"
    - name: email
      url: "https://www.gu.se/en/about/find-staff/andreaschatzopoulos"