title: mimavox
theme: charlolamode

menu:
  main:
      - name: Code
        url: /code/
        weight: 30
      - name: Research
        url: /research/
        weight: 20
      - name: Articles
        url: /articles/
        weight: 15

params:
  author: Andreas Chatzopoulos

  profileMode:
    # Disable to populate home page with 'mainSections' content
    enabled: true
    title: Andreas Chatzopoulos
    description: |
      
      University lecturer with a background in Cognitive
Science and extensive programming experience

  socialIcons:
    - name: mastodon
      url: "https://zirk.us/home"
    - name: github
      url: "https://github.com/mimavox"
    - name: linkedin
      url: "https://www.linkedin.com/in/chatzopoulos/"